# AuDeep AP - dnsmasq
# Colocar en /etc/dnsmasq.d/audeep.conf
interface=wlan0
dhcp-range=192.168.4.2,192.168.4.20,255.255.255.0,24h
dhcp-option=3,192.168.4.1
dhcp-option=6,192.168.4.1
server=8.8.8.8
log-queries
log-dhcp
address=/#/192.168.4.1
